insert into ORDER_POSITIONS (POSITION_ID, ARTICLE_ID, ARTICLE_QUANTITY)
VALUES (1, 1000, 1),
(2, 1001, 1);

insert into ORDERS (ORDER_ID, CUSTOMER_ID)
VALUES (1, 500);

insert into ORDERS_ORDER_POSITIONS (ORDER_ENTITY_ORDER_ID, ORDER_POSITIONS_POSITION_ID, ORDER_POSITIONS_KEY)
VALUES (1, 1, 10000),
       (1, 2, 10001);
       
      